In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
cols = ['user_id', 'item_id', 'rating', 'ts']
path = "../../../ml-1m/ratings.dat"
sep = "::"
base = pd.read_csv(path, sep=sep, names=cols)

D:\SDE\Anaconda\envs\cs\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


In [3]:
base = base.loc[base['rating'] >= 1].drop(['rating','ts'], axis=1).reset_index(drop=True)

In [4]:
user_list = sorted(list(set(base.user_id)))
item_list = sorted(list(set(base.item_id)))

In [5]:
uid, iid = len(user_list), len(item_list)

In [6]:
user_to_index_map = dict(zip(user_list, range(uid)))
item_to_index_map = dict(zip(item_list, range(iid)))

In [7]:
idx = list(base.index.values)
total_num = len(idx)
vad_num = int(total_num*0.2)
te_num = int(total_num*0.2)
tmp_idx = random.sample(idx,k=vad_num)
vad_data = base.iloc[tmp_idx,:].reset_index(drop=True)
tmp = base.drop(tmp_idx, axis=0).reset_index(drop=True)
idx = list(tmp.index.values)
tmp_idx = random.sample(idx,k=te_num)
test_data = tmp.iloc[tmp_idx,:].reset_index(drop=True)
train_data = tmp.drop(tmp_idx, axis=0).reset_index(drop=True)

In [8]:
train_data

user_id  item_id
0             1     1193
1             1      661
2             1     2355
3             1     1197
4             1     1287
...         ...      ...
600122     6040     1080
600123     6040     1089
600124     6040      562
600125     6040     1096
600126     6040     1097

[600127 rows x 2 columns]

In [9]:
train_set = dict()

In [14]:
for i in train_data.itertuples():
    train_set.setdefault(user_to_index_map.get(i[1]),list()).append(item_to_index_map.get(i[2]))

In [17]:
print(train_set.get(0))

[1104, 1104, 639, 2162, 1107, 1195, 581, 877, 2205, 2710, 970, 2586, 2483, 2889, 2592, 2128, 513, 47, 1025, 1574, 1421, 2102, 2969, 574, 740, 2557, 144, 0, 1781, 2488, 253, 964, 1117, 1848, 593, 1154]


In [1]:
import torch

In [6]:
a = torch.tensor([0]*100, dtype=torch.float)

In [7]:
a

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [10]:
a[[1]] = 1

In [11]:
a

tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
torch.eye(3,3)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [15]:
torch.zeros(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [22]:
torch.matmul(torch.eye(3,4), torch.eye(4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [43]:
torch.sum(torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.],[9.,10.,11.,12.]]),dim=1)

tensor([10., 26., 42.])

In [45]:
torch.mean(torch.sum(torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.],[9.,10.,11.,12.]]),dim=1))

tensor(26.)

In [44]:
torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.],[9.,10.,11.,12.]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])